<a href="https://colab.research.google.com/github/1NarendraSingh1/Fake-News-Classifier-using-Natural-Language-Processing-NLP/blob/main/Fake_news_classifier_stemm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Files Data science/fake_newsData.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [ ]:
df.shape

(20800, 5)

In [ ]:
df.describe()

id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [ ]:
df.columns

Index(['id', 'title', 'author', 'text', 'label'], dtype='object')

In [ ]:
df=df.dropna()

In [ ]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [ ]:
df.shape

(18285, 5)

In [ ]:
x=df.drop(['label'],axis=1)
y=df['label']

In [ ]:
x.shape,y.shape

((18285, 4), (18285,))

In [ ]:
import tensorflow as tf
tf.__version__

'2.17.1'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=1000

In [ ]:
messages=x.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.head(20)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
12  12  Russian Researchers Discover Secret Nazi Milit...   
13  13  US Officials See No Link Between Trump and Russia   
14  14  Re: Yes, There Are Paid Government Trolls On S...   
15  15  In Major League Soccer, Argentines Find a Home...   
16  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
17  17  Anonymous Donor Pays $2.5 Million To Release E...   
18  18                          FBI Closes In On Hillary!   
19  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   
21  21  Monica Lewinsky, Clinton Sex Scandal Set for ’...   
22  22  Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...   

                              author  \
0                      Darrell Lucus   
1                    Daniel J. Flynn   
2                 Consortiumnews.com   
3                    Jessica Purkiss   
4                     Howard Portnoy   
5                    Daniel Nussbaum   
7                    Alissa J. Rubin   
9       Megan Twohey and Scott Shane   
10                       Aaron Klein   
11                   Chris Tomlinson   
12                     Amando Flavio   
13                        Jason Ditz   
14                      AnotherAnnie   
15                     Jack Williams   
16  Michael Corkery and Stacy Cowley   
17                          Starkman   
18                           The Doc   
19                         Jeff Poor   
21                     Jerome Hudson   
22                           Pam Key   

                                                 text  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get the feeling your life circles the rou...  
2   Why the Truth Might Get You Fired October 29, ...  
3   Videos 15 Civilians Killed In Single US Airstr...  
4   Print \nAn Iranian woman has been sentenced to...  
5   In these trying times, Jackie Mason is the Voi...  
7   PARIS  —   France chose an idealistic, traditi...  
9   A week before Michael T. Flynn resigned as nat...  
10  Organizing for Action, the activist group that...  
11  The BBC produced spoof on the “Real Housewives...  
12  The mystery surrounding The Third Reich and Na...  
13  Clinton Campaign Demands FBI Affirm Trump's Ru...  
14  Yes, There Are Paid Government Trolls On Socia...  
15  Guillermo Barros Schelotto was not the first A...  
16  The scandal engulfing Wells Fargo toppled its ...  
17  A Caddo Nation tribal leader has just been fre...  
18  FBI Closes In On Hillary! Posted on Home » Hea...  
19  Wednesday after   Donald Trump’s press confere...  
21  Screenwriter Ryan Murphy, who has produced the...  
22  Sunday on MSNBC’s “AM Joy,” actor and director...

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[:20]

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr[:20]

[[474, 352, 115, 280, 81, 128, 451, 867, 998, 512],
 [347, 124, 613, 704, 932, 310, 816],
 [960, 629, 591, 177],
 [19, 683, 531, 548, 527, 893],
 [900, 932, 813, 807, 428, 730, 932, 929, 560, 941],
 [357, 368, 995, 267, 591, 169, 994, 845, 512, 388, 839, 602, 874, 802, 816],
 [269, 376, 832, 382, 375, 56, 524, 495, 954, 317, 120],
 [940, 891, 168, 549, 974, 643, 169, 491, 954, 317, 120],
 [441, 791, 862, 239, 813, 637, 907, 642, 169, 300],
 [775, 696, 845, 811, 220, 445, 533, 141],
 [275, 924, 983, 289, 168, 30, 34, 608, 374, 717, 880],
 [548, 172, 81, 637, 169, 974],
 [946, 427, 916, 245, 284, 204, 770, 57, 569],
 [693, 393, 375, 405, 627, 988, 26, 954, 317, 120],
 [941, 21, 409, 665, 80, 954, 317, 120],
 [68, 538, 850, 687, 645, 678, 467, 145, 672, 171],
 [765, 400, 124],
 [372, 66, 178, 470, 169, 415, 65, 816],
 [163, 170, 613, 777, 744, 97, 170, 715, 730],
 [799, 909, 169, 86, 874, 816]]

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 867 998 512]
 [  0   0   0 ... 932 310 816]
 [  0   0   0 ... 629 591 177]
 ...
 [  0   0   0 ... 954 317 120]
 [  0   0   0 ... 235 745 854]
 [  0   0   0 ...  94  88 522]]


In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 474, 352, 115,
       280,  81, 128, 451, 867, 998, 512], dtype=int32)

In [ ]:
## Creating model
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(LSTM(100))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model.summary())


In [ ]:
# # prompt: create model

# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(LSTM(100))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model.summary())



In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features)) # Remove input_length
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.build((None, sent_length)) # Assuming your input shape is (batch_size, sent_length)
print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (None, 20, 40)              │          40,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 96,501 (376.96 KB)

 Trainable params: 96,501 (376.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
# y = np.array(y) # Convert y to NumPy array
# model.fit(embedded_docs,y,validation_split=0.2,epochs=10,batch_size=64)
# y_pred=model.predict_classes(embedded_docs)
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y,y_pred)
# from sklearn.metrics import accuracy_score
# accuracy_score(y,y_pred)
# import numpy as np

In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.7859 - loss: 0.4314 - val_accuracy: 0.9052 - val_loss: 0.2121
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - accuracy: 0.9198 - loss: 0.1864 - val_accuracy: 0.9069 - val_loss: 0.2067
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9385 - loss: 0.1543 - val_accuracy: 0.9112 - val_loss: 0.2078
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9485 - loss: 0.1354 - val_accuracy: 0.9107 - val_loss: 0.2173
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9541 - loss: 0.1230 - val_accuracy: 0.9085 - val_loss: 0.2231
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - accuracy: 0.9607 - loss: 0.1063 - val_accuracy: 0.9060 - val_loss: 0.2511
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 33ms/step - accuracy: 0.9664 - loss: 0.0948 - val_accuracy: 0.9044 - val_loss: 0.2656
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9692 - loss: 0.0834 - val_ac

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred < 0).astype(int)  # Convert probabilities to class labels (0 or 1)

189/189 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step


In [ ]:
pd.DataFrame(y_pred).value_counts()

0
0    6035
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]])

In [ ]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
y_test

array([1, 0, 0, ..., 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917